research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and syntetize it into a report of maximum 800 words, be concise and to the point.
    Make sure the report contains all relevant information.
  expected_output: >
    A full report with maximum 800 words. Formatted as markdown without '```'
  agent: reporting_analyst

summarization_task:
  description: >
    Summarize the content of the report in a short summary.
  expected_output: >
    A structured output with all required information.
  agent: reporting_analyst
